name: Check spell

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip install invoke
          sudo apt-get install aspell aspell-es aspell-en
      - name: Run spell checker
        run: |
          inv spellcheck
