name: Check spell

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Install aspell (spell checker)
        run: |
          sudo apt-get install aspell aspell-es aspell-en

      - name: Run spell checker
        run: |
          inv spellcheck
