name: Check spell

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Install aspell (spell checker)
        run: |
          sudo apt-get install aspell aspell-es

      - name: Run spell checker
        run: |
          inv spellcheck
